craftycontroller:
  persistence:
    crafty-app-config:
      requests: 1Gi
      storageClassName: zfs-nvmeof
    crafty-servers:
      requests: 50Gi
      storageClassName: zfs-nvmeof
    crafty-backups:
      enabled: true
      requests: 200Gi
      storageClassName: zfs-nvmeof
    crafty-logs:
      enabled: true
      requests: 1Gi
      storageClassName: zfs-nvmeof
    crafty-home:
      enabled: true
      accessModes:
        - ReadWriteOnce
      mountPath: /home/crafty
      requests: 10Gi
      storageClassName: zfs-nvmeof

  services:
    https:
      type: ClusterIP
      ingress:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
          external-dns.alpha.kubernetes.io/target: ip.drewburr.com
          nginx.ingress.kubernetes.io/proxy-body-size: '0' # Disable size check
          nginx.ingress.kubernetes.io/configuration-snippet: |
            sub_filter '<a class="nav-link" href="/panel/contribute">' '<a class="nav-link" href="/panel/contribute" hidden=true>';
            sub_filter '<a class="nav-link" href="/panel/credits">' '<a class="nav-link" href="/panel/credits" hidden=true>';
            sub_filter '<a class="nav-link" href="https://discord.gg/9VJPhCE" target="_blank">' '<a class="nav-link" hidden=true>';
            sub_filter 'if (MFA_WARN) {' 'if (false) {';
        hosts:
          - host: derailed.crafty.drewburr.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: craftycontroller-ingress
            hosts:
              - derailed.crafty.drewburr.com
    minecraft:
      type: ClusterIP
      annotations:
        mc-router.itzg.me/externalServerName: derailed.mc.drewburr.com
    metrics:
      type: ClusterIP
      labels:
        metrics: 'true'
      ports:
        - name: metrics
          port: 19565
          protocol: TCP
    map:
      type: ClusterIP
      ports:
        - name: bluemap
          port: 8100
          protocol: TCP
      ingress:
        className: nginx-external
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
          nginx.ingress.kubernetes.io/backend-protocol: 'HTTPS'
          external-dns.alpha.kubernetes.io/target: ip.drewburr.com
          nginx.ingress.kubernetes.io/proxy-connect-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-read-timeout: "180"
          nginx.ingress.kubernetes.io/proxy-send-timeout: "180
        hosts:
          - host: derailed.map.drewburr.com
            paths:
              - path: /
                pathType: ImplementationSpecific
        tls:
          - secretName: bluemap-ingress
            hosts:
              - derailed.map.drewburr.com

  resources:
    limits:
      # cpu: 5
      memory: 12Gi
    requests:
      cpu: 1
      memory: 12Gi

  sftp:
    enabled: false

  podSecurityContext:
    fsGroup: 0

  securityContext:
    runAsNonRoot: true
    runAsUser: 1000 # Built-in Crafty user
    runAsGroup: 0 # Required for permissions

  serviceMonitors:
    - name: metrics
      endpoints:
        - interval: 15s
          path: /
          port: metrics
          scrapeTimeout: 10s
      selector:
        matchLabels:
          metrics: 'true'
      namespaceSelector:
        matchNames:
          - "{{ .Release.Namespace }}"

  tolerations:
    - key: compute
      operator: Exists
      effect: PreferNoSchedule

  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          preference:
            matchExpressions:
              - key: compute
                operator: In
                values:
                  - 'true'
