---
apiVersion: v2
name: home-assistant
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
dependencies:
  - name: home-assistant # https://github.com/pajikos/home-assistant-helm-chart
    repository: http://pajikos.github.io/home-assistant-helm-chart/
    version: ^0.3.41
