---
services:
  - name: pve-node-exporter
    ips:
      - 192.168.4.21
      - 192.168.4.22
      - 192.168.4.23
      - 192.168.4.24
      - 192.168.4.25
      - 192.168.4.26
      - 192.168.4.27
      - 192.168.4.28
      - 192.168.4.29
  - name: storage-node-exporter
    ips:
      - 192.168.4.31
  - name: backup-node-exporter
    ips:
      - 192.168.4.2
  - name: generic-node-exporter
    ips:
      - 192.168.1.177
  - name: remote-node-exporter
    ips:
      - 193.23.250.33
    port: 19100

endpoint:
  honorLabels: true
  path: /metrics
  port: http
  scheme: http
  scrapeTimeout: 30s
port: 9100
labels:
  app: node-exporter
