apiVersion: v2
name: plex-config
description: A Helm chart for configuring Plex
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
- name: library
  version: 0.0.0
  repository: file://../library
